# Generated by Django 2.2.1 on 2019-11-23 20:18

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('date', models.DateField(auto_now=True)),
                ('check_in', models.TimeField(auto_now=True)),
                ('check_out', models.TimeField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='myapp.Host')),
            ],
        ),
    ]
