# Generated by Django 2.2.1 on 2019-11-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191124_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
