# Generated by Django 2.2.1 on 2019-11-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
